rsa:
  public-key: classpath:certs/public.pem


server:
  port: 9000
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: edge-service
    gateway:
      routes:
        - id: userprofile-route
          uri: ${USERPROFILE_SERVICE_URL:http://localhost:9010}/api/v1/userprofile
          predicates:
            - Path=/userprofile/**
management:
  endpoints:
    web:
      exposure:
        include: refresh
        
  
