rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem


server:
  port: 9010
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  main:
    allow-circular-references: true
  application:
    name: userprofile-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show_sql: true
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/blogdb
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  jackson:
    serialization:
      fail-on-empty-beans: 'false'

management:
  endpoints:
    web:
      exposure:
        include: refresh